Fork test update
orbcollective/linear-pools pull request #31
Opened 2023-03-29 17:11 UTC by baileyspraggins

2023-03-30 22:37 UTC, rabmarut commented
@baileyspraggins I've merged #30. Please merge master into this branch and resolve the conflicts; then I can take a look at it.

2023-03-30 22:38 UTC, baileyspraggins commented
> @baileyspraggins I've merged #30. Please merge master into this branch and resolve the conflicts; then I can take a look at it.

Perfect! On it now!

2023-04-03 21:38 UTC, rabmarut requested changes

2023-04-03 21:38 UTC, rabmarut commented on pkg/fork-tests/tests/20221114-yearn-linear-pool/readme.md
> +- [`YearnShareValueHelper` artifact](./artifact/YearnShareValueHelper.json)
We don't need this artifact because this contract never gets deployed on its own; it is inherited by the Pool.
```suggestion
```

2023-04-03 21:38 UTC, rabmarut commented on pkg/fork-tests/tests/20221207-aave-rebalanced-linear-pool-v4/input.ts
> +const BaseVersion = { version: 3, deployment: '20221207-aave-rebalanced-linear-pool-v4' };
This should match, right?
```suggestion
const BaseVersion = { version: 4, deployment: '20221207-aave-rebalanced-linear-pool-v4' };
```

2023-04-03 21:38 UTC, rabmarut commented on pkg/fork-tests/tests/20221207-aave-rebalanced-linear-pool-v4/readme.md
> +- [`AaveLinearPoolRebalancer` artifact](./artifact/AaveLinearPoolRebalancer.json)
Looks like these artifacts are missing.

2023-04-03 21:38 UTC, rabmarut commented on pkg/fork-tests/tests/20221207-aave-rebalanced-linear-pool-v4/test/test.fork.ts
>          version: 3,
```suggestion
        version: 4,
```

2023-04-03 21:38 UTC, rabmarut commented on pkg/fork-tests/tests/20221207-aave-rebalanced-linear-pool-v4/test/test.fork.ts
>          version: 3,
```suggestion
        version: 4,
```

2023-04-03 21:38 UTC, rabmarut commented on pkg/fork-tests/tests/20230103-erc4626-linear-pool-v3/input.ts
> +const BaseVersion = { version: 1, deployment: '20230103-erc4626-linear-pool-v3' };
```suggestion
const BaseVersion = { version: 3, deployment: '20230103-erc4626-linear-pool-v3' };
```

2023-04-03 21:38 UTC, rabmarut commented on pkg/fork-tests/tests/20230103-erc4626-linear-pool-v3/readme.md
> +- [`ERC4626LinearPoolRebalancer` artifact](./artifact/ERC4626LinearPoolRebalancer.json)
Artifacts missing

2023-04-03 21:38 UTC, rabmarut commented on pkg/fork-tests/tests/20230103-erc4626-linear-pool-v3/test/test.fork.ts
>          version: 1,
```suggestion
        version: 3,
```

2023-04-03 21:38 UTC, rabmarut commented on pkg/fork-tests/tests/20230103-erc4626-linear-pool-v3/test/test.fork.ts
>          version: 1,
```suggestion
        version: 3,
```

2023-04-03 21:38 UTC, rabmarut commented on pkg/fork-tests/tests/20230106-silo-linear-pool/index.ts
>      // SiloLinearPools require an Silo Token
```suggestion
    // SiloLinearPools require a Silo Token
```

2023-04-03 21:38 UTC, rabmarut commented on pkg/fork-tests/tests/20230106-silo-linear-pool/readme.md
> +- [Goerli testnet addresses](./output/goerli.json)
None of the other readmes include goerli addresses - why switch the convention here?

2023-04-03 21:38 UTC, rabmarut commented on pkg/fork-tests/tests/20230110-tetu-linear-pool/build-info/ITetuController.json
Do we really need this one, or can we delete it?

2023-04-04 01:55 UTC, baileyspraggins commented on pkg/fork-tests/tests/20230110-tetu-linear-pool/build-info/ITetuController.json
Yes because the Tetu Controller is not included within the main build info. Since Tetu is not going to be released, should I open another PR deleting all depreciated linear pools or create a depreciated folder to store them?

2023-04-04 14:17 UTC, rabmarut commented
@baileyspraggins I think we should also remove the dates from our fork tests because they aren't really relevant. These are rolling releases; the date-stamped deployments already live in the monorepo.

2023-04-04 15:53 UTC, rabmarut approved these changes

2023-04-04 15:53 UTC, merged