Deprecate update
orbcollective/linear-pools pull request #32
Opened 2023-04-04 15:40 UTC by baileyspraggins

This PR deprecates the Tetu Linear Pool by moving both the fork-tests and linear pool contracts to `deprecated` folders.

2023-04-04 19:57 UTC, joaobrunoah approved these changes

2023-04-05 18:25 UTC, rabmarut requested changes

2023-04-05 18:25 UTC, rabmarut commented on pkg/fork-tests/tests/tetu-linear-pool/readme.md
This file is empty but it still seems to exist. Let's delete it (and the `tetu-linear-pool` directory containing it) entirely.

2023-04-05 19:02 UTC, baileyspraggins commented on pkg/fork-tests/tests/tetu-linear-pool/readme.md
AHHHH I keep deleting it and it comes back lol

2023-04-05 19:06 UTC, baileyspraggins commented on pkg/fork-tests/tests/tetu-linear-pool/readme.md
Looks to be gone now

2023-04-05 19:25 UTC, rabmarut approved these changes

2023-04-05 19:26 UTC, merged