Documenting how to create a new linear pool in README.md
orbcollective/linear-pools pull request #5
Opened 2023-01-05 14:11 UTC by joaobrunoah

2023-01-06 15:33 UTC, baileyspraggins requested changes

2023-01-06 15:33 UTC, baileyspraggins commented on README.md
> +(don't need to rename now).
In the end of this process --> Once the contracts are compiled

2023-01-06 18:19 UTC, joaobrunoah commented on README.md
> +
The rebalancing section of LinearPool unit test is only to check if get rate reverts when a malicious query runs (number 4). That's why I didn't put it in here.

2023-01-06 18:21 UTC, baileyspraggins commented on README.md
> +
Gotcha. Thanks for clarifying!

2023-01-12 15:47 UTC, baileyspraggins approved these changes

2023-01-12 15:47 UTC, merged